spring:
  application:
    name: running-event
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/running_event
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          strava:
            client-id:
            client-secret:
            scope: activity:read_all
            token-name: access_token
            authentication-scheme: query
            client-authentication-scheme: form
            client-authentication-method: post
            authorization-grant-type: authorization_code
            client-name: Strava
            redirect-uri: "{baseUrl}/login/oauth2/code/strava"
        provider:
          strava:
            token-uri: https://www.strava.com/oauth/token
            authorization-uri: https://www.strava.com/oauth/authorize
            user-info-uri: https://www.strava.com/api/v3/athlete
            user-name-attribute: id
server:
  error:
    whitelabel:
      enabled: false
